#WAPS to calculate volume of a cuboid by user(float values)
x=input("enter the length\n")
y=input("enter the bridth\n")
z=input("enter  the height\n")
l=float(x)
b=float(y)
h=float(z)
volume=l*b*h
print("volume of a cuboid is: ",volume)
input()
